#!/usr/bin/env python
# ftclient
# CS372 Spring 2018
# -----------------
# Name: Zachary Thomas
# Email: thomasza@oregonstate.edu
# Date: 5/19/2018
# ------------------------------------
# Set up file transfer with server.
# ------------------------------------
# Cited references:
# Lecture 15: Socket Programming Primer 

from socket import *
import sys

# start_up
# -------
# setup the server, get a handle, listen for connections.
# when a connection is made accept and receive messages
# until one side quits. When that happens resume listening.
def start_up():
	serverName = 'servername'
	serverPort = 12000
	clientSocket = socket(AF_INET, SOCK_STREAM)
	clientSocket.connect((serverName, serverPort))
	sentence = raw_input('enter something to send')
	clientSocket.send(sentence)
	modifiedSentence = clientSocket.recv(1024)
	print'From Server:', modifiedSentence
	clientSocket.close()	

# receive_message
# ------------
# get a message from the client.
# If the client quit we return to listening
# for a new connection.
#
# connectionSocket: The current socket being used.
#
# return: Returns true if received a message. Returns false if the client quit.
def receive_message(connectionSocket):
	#get message from client and remove newline
	clientMessage = connectionSocket.recv(1024)
	clientMessage = clientMessage.rstrip()

	#if client quit stop here
	if(clientMessage == "\quit"):
		connectionSocket.close()
		return False
	
	#print clients message	
	print clientMessage
	return True

# send_message
# ------------
# send a message to the client or quit.
# If we quit let the client know.
#
# handle: The handle the user selected previously.
# connectionSocket: The current socket being used.
#
# return: Returns true if we sent a message. Returns false if we quit.
def send_message(handle, connectionSocket):
	#get message from user
	serverMessage = raw_input(handle + "> ")
		
	#if we typed /quit instead of a message let client know
	if(serverMessage == "\quit"):
		connectionSocket.send(serverMessage + '\n')
		connectionSocket.close()
		return False

	#send message to client
	connectionSocket.send(handle + "> " + serverMessage[:500] + '\n')
	return True

def main():
	start_up()

if __name__ == "__main__":
	main()
